# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

logLevel: debug
logToStdout: both

macros:
  DEFAULT_THREADS: 12
  DEFAULT_CTX_SIZE: 66000
  DEFAULT_GPU_LAYERS: 12

models:
  gemma-4-26B-A4B-it:
    description: |
      Gemma 4 is a versatile family of multimodal open-weights models from Google DeepMind,
      capable of processing text and images across more than 140 languages. Featuring both
      Dense and Mixture-of-Experts architectures, the models offer a significant 256K token
      context window and are available in pre-trained or instruction-tuned variants. They are
      specifically designed to excel at high-level reasoning, coding, and text generation tasks.
    cmd: |
      llama-server \
        -hf 'unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_M' \
        --jinja \
        --port ${PORT} \
        --threads ${DEFAULT_THREADS} \
        --ctx-size ${DEFAULT_CTX_SIZE} \
        --gpu-layers 6 \
        -ctk q4_0 \
        -ctv q4_0 \
        --temp 1.0 \
        --top-p 0.75 \
        --top-k 64.0 \
        --min-p 0.1 \
        --n-cpu-moe 19 \
        --spec-draft-n-max 2
  Qwen3.6-35B-A3B:
    description: |
      Qwen3.6 is Alibaba’s new family of multimodal hybrid-thinking
      models, including Qwen3.6-35B-A3B. It delivers top performance
      for its size, supports 256K context across 201 languages.
      It excels in agentic coding, vision, chat tasks.
    cmd: |
      llama-server \
        -hf 'unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_M' \
        --jinja \
        --port ${PORT} \
        --threads ${DEFAULT_THREADS} \
        --ctx-size ${DEFAULT_CTX_SIZE} \
        --gpu-layers 7 \
        -ctk q4_0 \
        -ctv q4_0 \
        --temp 1.0 \
        --top-p 0.95 \
        --top-k 20.0 \
        --min-p 0.1 \
        --n-cpu-moe 19 \
        --spec-draft-n-max 2
  Mellum2-12B-A2.5B-Instruct:
    ttl: 90
    description: |
      Mellum 2 Instruct is a Mixture-of-Experts assistant
      model that answers directly, without an externalized
      chain of thought.
    cmd: |
      llama-server \
        -hf 'JetBrains/Mellum2-12B-A2.5B-Instruct-GGUF-Q4_K_M:Q4_K_M' \
        --jinja \
        --port ${PORT} \
        --threads ${DEFAULT_THREADS} \
        --ctx-size ${DEFAULT_CTX_SIZE} \
        --gpu-layers 99 \
        -ctk q4_0 \
        -ctv q4_0 \
        --temp 0.7 \
        --top-p 0.90 \
        --top-k 20.0 \
        --min-p 0.01 \
        --n-cpu-moe 19
