name: 'Update Nix flake'

on:
  schedule:
    # Runs every three hours at 01:00, 04:00, 07:00, 10:00, 13:00, 16:00, 19:00, and 22:00 UTC daily.
    - cron: '0 1,4,7,10,13,16,19,22 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-nix-flake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GITHUB_TOKEN: "${{ secrets.TOKEN }}"

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository }}"
          token: "${{ env.GITHUB_TOKEN }}"

      - name: 'Install Nix'
        uses: cachix/install-nix-action@v31

      - name: 'Update Nix flake'
        shell: bash
        run: |
          echo '----- Creating a new environment with helper programs -----'
          echo '> nix flake update --verbose'
          nix flake update --verbose

      - name: 'Commit changes'
        shell: bash
        run: |
          echo "> USERNAME='github-actions[bot]'"
          USERNAME='github-actions[bot]'
          echo "> EMAIL='41898282+github-actions[bot]@users.noreply.github.com'"
          EMAIL='41898282+github-actions[bot]@users.noreply.github.com'
          echo '> git config --local user.name $USERNAME'
          git config --local user.name $USERNAME
          echo '> git config --local user.email $EMAIL'
          git config --local user.email $EMAIL
          echo '> git add -u'
          git add -u

          if [ -n "$(git status --porcelain)" ]; then
            echo "> git commit -m 'bot: Updated \`flake.lock\`'"
            git commit -m 'bot: Updated `flake.lock`'
          fi

      - name: 'Push changes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: "${{ env.GITHUB_TOKEN }}"
          branch: "${{ github.ref }}"
